### ISSUE TITLE
의안 정보 api test

### ISSUE THREAD

**Issue by chobuisness** [ogongchill/korean-national-assembly-legislation-api-java#1]

**Comment by gzcxadfzc** [comment]
의안정보 응답 예시는 
[IROS4_OA_DV_0401_OpenAPI활용가이드_의안정보(국회사무처)_v1.30.pdf](https://github.com/user-attachments/files/18076256/IROS4_OA_DV_0401_OpenAPI._._v1.30.pdf)
[IROS4_OA_DV_0401_OpenAPI활용가이드_의안정보(국회사무처)_v1.30.docx](https://github.com/user-attachments/files/18076260/IROS4_OA_DV_0401_OpenAPI._._v1.30.docx)
확인 가능한데 오탈자나 태그가 안닫혀있는 등의 형식이 올바르지 않은 경우가 있음
예시 응답 xml파일 추가 해서 올려놓겠음

**Comment by chobuisness** [comment]
> ### 의안/청원 접수정보 국회의원 목록 조회 이상
> <img alt="스크린샷 2024-12-11 오후 12 20 34" width="491" src="https://private-user-images.githubusercontent.com/190695306/394556078-711fc482-e178-4f0e-ba99-4e2429a6c29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDU4NTMsIm5iZiI6MTczMzkwNTU1MywicGF0aCI6Ii8xOTA2OTUzMDYvMzk0NTU2MDc4LTcxMWZjNDgyLWUxNzgtNGYwZS1iYTk5LTRlMjQyOWE2YzI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwODI1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODRhNjcwZmJjNWFjZWZjNTcwYjhjYTUyNDI2OTkyNzJlMjljMWJmMTQ2ZWFjOTFiNzQ1MTY1OGE4YTdiZDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.chJp3hQw8BIJqsSUL1IRZZ_FwW6_R2ma-CsaIsqsDRc">
> 
> 직접 디버깅 해보면 body 에 아예 응답 자체가 안실림


이거 Request Url query param 생성할때 필드명대로 안들어가고 camel case 로 변경되어 들어가서 발생한 문제임.

`@JsonProperty` 를 통해서 명시적으로 지정해서 해결함
