### ISSUE TITLE
롬복 라이브러리 의존성 제거

### ISSUE THREAD

**Issue by chobuisness** [ogongchill/korean-national-assembly-legislation-api-java#2]
## 롬복 사용 시 오류 발생 가능성
<img width="1331" alt="스크린샷 2024-12-09 오후 11 08 10" src="https://github.com/user-attachments/assets/9b1be4bb-5f98-47f3-a251-c19ccd2349f7">

- `@Data` 사용 중 컴파일 단계에서 getter 인식 못하는 오류
- 자세한 이유는 나도 모름
  - 근데 웬만해서는 다른 라이브러리 코드는 걷어내는게 좋을듯

**Comment by gzcxadfzc** [comment]
롬복척결 확인햇습니다
